---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keyline.keyline.dev
  resources:
  - keylineapplications
  - keylineroleassignments
  - keylineroles
  - keylineusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyline.keyline.dev
  resources:
  - keylineapplications/finalizers
  - keylineroleassignments/finalizers
  - keylineroles/finalizers
  - keylineusers/finalizers
  verbs:
  - update
- apiGroups:
  - keyline.keyline.dev
  resources:
  - keylineapplications/status
  - keylineroleassignments/status
  - keylineroles/status
  - keylineusers/status
  verbs:
  - get
  - patch
  - update
