apiVersion: keyline.keyline.dev/v1alpha1
kind: KeylineUser
metadata:
  labels:
    app.kubernetes.io/name: keyline-operator
    app.kubernetes.io/managed-by: kustomize
  name: keylineuser-sample
spec:
  # TODO(user): Add fields here
